project:
  type: website

website:
  google-analytics: "G-SDG552HSPC"
  search: false
  title: "Harry Zhong"
  favicon: logo.png
  navbar:
    pinned: true
    left:
      - text: "{{<fa microscope>}} The Lab"
        href: the_lab.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/harry2687/
      - icon: github
        href: https://github.com/Harry2687
      - icon: envelope
        href: mailto:h.zhong2687@gmail.com

format:
  html:
    pagetitle: "Harry Zhong"
    theme: 
      dark: [darkly, custom.scss]
      light: [flatly, custom.scss]
    toc: true

editor: source

execute: 
  freeze: auto