---
title: "My Timeline"
---

## {{<fa hourglass-half>}} Future Goals

#### Qualify as a Fellow Actuary (FIAA).

#### Learn about data science!

## {{<fa square-check>}} Past Achievements

### 2023

---

#### Qualified as an Associate Actuary (AIAA).
- Studied and passed **Asset Liability Management** and **Communication, Modelling and Professionalism**, thus completing the **Actuary Program** while working at EBM.

---

#### Graduated with Bachelor of Science (Actuarial Science) (Honours).
- 78% Course weighted average.
- Completed **Data Analytics Principles** and **Actuarial Control Cycle** subjects as part of the Actuaries Institute [**Actuary Program**](https://www.actuaries.asn.au/education-program/actuary-program){target="_blank"}.
- Completed my honours dissertation (graded 82%): [Comparing Stochastic and Constant Volatility Returns Distributions using the Heston Model](https://www.researchgate.net/publication/372915363_Comparing_Stochastic_and_Constant_Volatility_Returns_Distributions_using_the_Heston_Model){target="_blank"}.

### 2022

---

##### Started my first graduate job at [EBM Insurance & Risk](https://www.ebminsurance.com.au/){target="_blank"}.

### 2021

---

##### Graduated with Bachelor of Science (Actuarial Science) with Distinction.
- 85% Course weighted average.
- Obtained all Actuaries Institute [**Foundation Program**](https://www.actuaries.asn.au/education-program/foundation){target="_blank"} exemptions.
- Recipient of the Curtin Excellence Scholarship.